### PR TITLE
Pnda 4904 alternate config

### PR DESCRIPTION
**Pull request by klyr**

### CODE REVIEW

**Comment by trsmith2** [comment]
Does the change to safe_load impact implicit conversion of scalar true/false (or any other field we use in the configuration) ?

**Comment by klyr** [comment]
Good point.

According to PyYAML documentation `safe_load recognizes only standard YAML tags and cannot construct an arbitrary Python object`

So, it should be OK.
Nevertheless, if you think this change is too sensible, I can remove this change

**Comment by klyr** [comment]
safe_load() modified back to load()

**Comment by jgarnier** [comment]
thanks @klyr for this contribution !

**Pull request merged**
